Repository 0xsend/sendapp, pull requests merged in 2025-05, with the labels that each got.

#1456 Too many files open error
  apps/next/next.config.js
Labels: kwaii, refactor, performance

#1458 Removed viem from optimizePackageImports
  apps/next/next.config.js
Labels: bug, kwaii

#1473 Friends page
  apps/next/pages/account/affiliate.tsx
  packages/app/components/ReferralLink.tsx
  packages/app/components/icons/IconBirthday.tsx
  packages/app/components/icons/index.tsx
  packages/app/features/affiliate/screen.skiptest.tsx
  packages/app/features/affiliate/screen.tsx
  packages/app/features/affiliate/utils/useFriends.ts
  packages/app/utils/useHoverStyles.ts
  packages/ui/src/components/Link.tsx
  supabase/database-generated.types.ts
  supabase/migrations/20250512225147_add_more_fields_to_get_referrals.sql
  supabase/tests/profile_lookup_test.sql
Labels: kwaii, feature, refactor

#1474 Fixed no friends message
  packages/app/components/ReferralLink.tsx
  packages/app/features/affiliate/screen.tsx
Labels: kwaii, feature, refactor

#1475 bb/fix specs
  packages/app/features/home/InvestmentBalanceList.tsx
  packages/app/utils/useSearchResultHref.tsx
  packages/playwright/tests/fixtures/earn/EarnDepositPage.ts
  packages/playwright/tests/fixtures/swap/index.ts
  packages/playwright/tests/send.onboarded.spec.ts
  packages/playwright/tests/swap.onboarded.spec.ts
  packages/snaplet/.snaplet/snaplet-client.d.ts
Labels: bug, kwaii, feature, refactor, tests

#1479 Fixed tag availability check
  packages/api/src/routers/tag/router.ts
Labels: bug, kwaii, refactor

#1490 Fixed duplicated foreign key
  packages/api/src/routers/tag/router.ts
  packages/snaplet/.snaplet/dataModel.json
  packages/snaplet/.snaplet/snaplet-client.d.ts
  packages/snaplet/.snaplet/snaplet.d.ts
  supabase/database-generated.types.ts
  supabase/migrations/20250520225147_fix_duplicated_foreign_key.sql
Labels: kwaii, refactor

#1496 Improved UX on trade summary
  packages/app/features/swap/summary/screen.tsx
  packages/app/utils/userop.ts
Labels: kwaii, feature, refactor

#1497 Fixed sign up issues
  packages/app/features/auth/sign-up/screen.tsx
  packages/app/utils/tags/useValidateSendtag.ts
Labels: bug, kwaii, feature, refactor

#1498 Recent senders
  packages/app/features/activity/utils/useRecentSenders.ts
  packages/app/features/send/screen.tsx
  supabase/database-generated.types.ts
  supabase/migrations/20250523225148_recent_senders.sql
Labels: kwaii, feature

#1526 fix: fix normalizeRedirectUrl to preserve query parameters
  apps/next/utils/normalizeRedirectUrl.test.ts
  apps/next/utils/normalizeRedirectUrl.ts
  apps/next/utils/userProtected.ts
Labels: bug, kwaii, refactor, tests

#1532 Added today birthday feed restrictions
  supabase/migrations/20250526225150_today_birthday_restrictions.sql
Labels: kwaii, feature

#1533 Favorites feed improvements
  packages/app/features/send/suggestions/SendSuggestions.tsx
  supabase/migrations/20250526225151_favorite_senders_changes.sql
Labels: bug, kwaii, feature, refactor, security

#1534 Top senders feed
  packages/app/features/send/screen.tsx
  packages/app/features/send/suggestions/SendSuggestions.tsx
  packages/app/features/send/suggestions/useTopSenders.ts
  supabase/database-generated.types.ts
  supabase/migrations/20250527225151_top_senders.sql
Labels: kwaii, feature

#1548 Improved top senders query
  supabase/migrations/20250528225151_improve_top_senders.sql
Labels: kwaii, refactor, performance

#1564 Token activity row UI changes
  packages/app/features/activity/ActivityAvatar.tsx
  packages/app/features/home/TokenActivityFeed.tsx
  packages/app/features/home/TokenActivityRow.tsx
  packages/app/features/home/utils/useTokenActivityRowSize.ts
  packages/app/utils/activity.test.tsx
  packages/app/utils/activity.tsx
Labels: kwaii, feature, refactor
