Repository 0xsend/sendapp, pull requests merged in 2025-03, with the labels that each got.

#1127 Patch send ceiling trigger repeated sends
  supabase/migrations/20250225053238_patch_send_ceiling_trigger_repeated_sends.sql
Labels: kwaii, feature

#1126 Account page refresh
  packages/app/components/icons/IconGroup.tsx
  packages/app/components/icons/index.tsx
  packages/app/features/account/__snapshots__/screen.test.tsx.snap
  packages/app/features/account/screen.tsx
Labels: kwaii, feature, refactor

#1153 fix usdc conversion rate
  packages/app/utils/useSendAccountBalances.ts
Labels: bug, kwaii

#1154 fix(playwright): more stable tests
  .github/workflows/ci.yml
  packages/playwright/tests/fixtures/profiles/test.ts
  packages/playwright/tests/fixtures/sendtags/checkout/page.ts
  packages/playwright/tests/profile.anon.spec.ts
  packages/playwright/tests/profile.logged-in.spec.ts
  packages/playwright/tests/profile.onboarded.spec.ts
Labels: bug, kwaii, tests

#1168 deploy
  packages/app/components/icons/IconFingerprint.tsx
  packages/app/components/icons/index.tsx
  packages/app/data/sendtags.test.ts
  packages/app/data/sendtags.ts
  packages/app/features/account/settings/SettingsLinks.tsx
  packages/app/provider/scroll/ScrollDirectionProvider.tsx
Labels: bug, kwaii, feature, refactor, tests

#1177 Deploy
  apps/distributor/src/distributorv2.ts
  apps/next/pages/[tag].tsx
  apps/next/pages/_app.tsx
  packages/api/src/routers/tag.ts
  packages/app/features/account/sendtag/add/AddSendtagsForm.tsx
  packages/app/features/account/sendtag/checkout/checkout-form.tsx
  packages/app/features/account/sendtag/checkout/checkout-utils.ts
  packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx
  packages/app/features/account/sendtag/checkout/screen.test.tsx
  packages/app/utils/useReferralCodeCookie.ts
  packages/app/utils/useReferrer.ts
  packages/app/utils/zod/sendtag.ts
  packages/playwright/tests/account-sendtag-checkout.onboarded.spec.ts
  packages/snaplet/.snaplet/dataModel.json
  supabase/database-generated.types.ts
  supabase/migrations/20250316212705_add_referrals_created_at_and_referrer_lookup.sql
Labels: bug, kwaii, feature, refactor

#1184 feat: devcontainer
  .devcontainer/devcontainer.Dockerfile
  .devcontainer/devcontainer.json
  .env.local.template
  .github/dependabot.yml
  Tiltfile
  packages/temporal/src/client.ts
Labels: kwaii, feature, refactor

#1188 Fix temporal activity handler
  supabase/migrations/20250328184405_fix_temporal_activity_handler.sql
Labels: bug, kwaii, refactor, performance

#1163 Fix Onramps redirection and premature closing.
  apps/next/pages/deposit/success/callback.tsx
  packages/app/features/deposit/coinbase/screen.test.tsx
  packages/app/features/deposit/coinbase/screen.tsx
  packages/app/features/deposit/components/CoinbaseOnrampVerifyScreen.test.tsx
  packages/app/features/deposit/components/CoinbaseOnrampVerifyScreen.tsx
  packages/app/features/deposit/components/OnrampFlow.tsx
  packages/app/features/deposit/components/SuccessCallback.tsx
  packages/app/package.json
  packages/app/provider/onchainkit/index.tsx
  packages/app/utils/useCoinbaseOnramp.test.tsx
  packages/app/utils/useCoinbaseOnramp.ts
  yarn.lock
Labels: bug, kwaii, feature, refactor, tests
