Repository 0xsend/sendapp, pull requests merged in 2025-02, with the labels that each got.

#1054 Remove hasBeenLongEnough in confirm screen
  packages/app/features/send/confirm/screen.tsx
Labels: kwaii, refactor

#1069 use floor in formatAmount to avoid round up
  packages/app/utils/formatAmount.test.ts
  packages/app/utils/formatAmount.ts
Labels: kwaii, refactor, tests

#1068 Handle rounding errors in multipliers
  packages/app/utils/distributions.ts
Labels: bug, kwaii

#1067 Hide progress when no send_slash exists
  packages/app/features/account/rewards/activity/screen.tsx
Labels: bug, kwaii, refactor

#1071 deploy
  packages/app/components/MobileButtonRowLayout.tsx
  packages/app/data/coins.ts
  packages/app/features/account/rewards/activity/screen.tsx
  packages/app/features/account/rewards/screen.tsx
  packages/app/features/activity/ActivityRow.test.tsx
  packages/app/features/home/TokenDetails.tsx
  packages/app/features/send-token-upgrade/screen.tsx
  packages/app/features/send/SendAmountForm.tsx
  packages/app/features/send/confirm/screen.tsx
  packages/app/utils/activity.test.ts
  packages/app/utils/activity.ts
  packages/app/utils/distributions.ts
  packages/app/utils/formatAmount.test.ts
  packages/app/utils/formatAmount.ts
  packages/app/utils/zod/activity/SendAccountTransfersEventSchema.test.ts
  packages/app/utils/zod/activity/TagReceiptUSDCEventSchema.test.ts
  packages/app/utils/zod/activity/__snapshots__/index.test.ts.snap
  packages/contracts/script/gen-dist-merkle-tree.ts
Labels: kwaii, feature, refactor, tests

#1073 Adjust memoized safe area insets
  packages/app/components/MobileButtonRowLayout.tsx
  packages/ui/src/utils/useSafeAreaInsets.ts
Labels: kwaii, refactor

#1074 add safe area margin for Toast
  packages/ui/src/components/NativeToast.tsx
Labels: kwaii, feature

#1079 fix SSR problems for safe area insets
  packages/ui/src/utils/useSafeAreaInsets.ts
Labels: bug, kwaii, refactor

#1082 Fixed failing unit tests
  packages/app/features/deposit/__snapshots__/screen.test.tsx.snap
  packages/app/features/deposit/screen.test.tsx
  packages/app/utils/useCoinbaseOnramp.test.ts
  packages/app/utils/useCoinbaseOnramp.test.tsx
  packages/workflows/tsconfig.json
Labels: kwaii, refactor, tests

#1080 try module state and cache for safearea
  packages/ui/src/utils/useSafeAreaInsets.ts
Labels: kwaii, refactor, performance

#1081 Moved profile modal to param
  packages/app/features/profile/__snapshots__/screen.test.tsx.snap
  packages/app/features/profile/components/ProfileAboutTile.tsx
  packages/app/features/profile/components/ProfileDetailsModal.tsx
  packages/app/features/profile/components/ProfileHeader.tsx
  packages/app/features/profile/screen.test.tsx
  packages/app/features/profile/screen.tsx
  packages/app/features/send/SendAmountForm.tsx
  packages/app/routers/params.tsx
Labels: kwaii, feature, refactor

#1087 Refactor usePwa to be a hook
  packages/ui/src/utils/usePwa.ts
Labels: kwaii, refactor

#1093 Sendtags revamp
  apps/next/pages/account/sendtag/add.tsx
  apps/next/pages/account/sendtag/checkout.tsx
  packages/app/components/layout/RowLabel.tsx
  packages/app/data/coins.ts
  packages/app/data/sendtags.ts
  packages/app/features/account/components/editProfile/screen.tsx
  packages/app/features/account/sendtag/add/AddSendtagsForm.tsx
  packages/app/features/account/sendtag/add/AddSendtagsScreen.tsx
  packages/app/features/account/sendtag/checkout/SendTagPricingDialog.tsx
  packages/app/features/account/sendtag/checkout/checkout-form.tsx
  packages/app/features/account/sendtag/checkout/checkout-utils.ts
  packages/app/features/account/sendtag/checkout/components/checkout-confirm-button.tsx
  packages/app/features/account/sendtag/checkout/screen.tsx
  packages/app/features/account/sendtag/screen.test.tsx
  packages/app/features/account/sendtag/screen.tsx
  packages/app/features/account/settings/SettingsLinks.tsx
  packages/app/features/account/settings/backup/create.tsx
  packages/app/features/account/settings/backup/index.tsx
  packages/app/features/account/settings/components/Section.tsx
  packages/app/features/account/settings/components/SettingsHeader.tsx
  packages/app/features/account/settings/personal-info.tsx
  packages/app/utils/SchemaForm.tsx
  packages/playwright/tests/account-sendtag-add.onboarded.spec.ts
  packages/playwright/tests/account-sendtag-checkout.onboarded.spec.ts
  packages/playwright/tests/fixtures/checkout/page.ts
  packages/playwright/tests/fixtures/sendtags/add/index.ts
  packages/playwright/tests/fixtures/sendtags/add/page.ts
  packages/playwright/tests/fixtures/sendtags/add/test.ts
  packages/playwright/tests/fixtures/sendtags/checkout/index.ts
  packages/playwright/tests/fixtures/sendtags/checkout/page.ts
  packages/playwright/tests/fixtures/sendtags/checkout/test.ts
  packages/ui/src/components/FadeCard.tsx
  packages/ui/src/components/LinkableButton.tsx
  packages/ui/src/components/index.ts
Labels: kwaii, feature, refactor

#1125 Tags buttons position unification
  packages/app/features/account/sendtag/add/AddSendtagsForm.tsx
  packages/app/features/account/sendtag/checkout/checkout-form.tsx
  packages/app/features/account/sendtag/checkout/screen.tsx
  packages/app/features/account/sendtag/screen.tsx
Labels: documentation, kwaii, feature, refactor
