Repository 0xsend/sendapp, pull requests merged in 2025-04, with the labels that each got.

#1208 Decrease pairs being swapped in playwright
  packages/playwright/tests/swap.onboarded.spec.ts
Labels: kwaii, refactor

#1220 Some swap UI/UX polishes
  packages/app/components/FormFields/CoinField.tsx
  packages/app/features/home/TokenBalanceList.tsx
  packages/app/features/home/screen.tsx
  packages/app/features/swap/form/__snapshots__/screen.test.tsx.snap
  packages/app/features/swap/form/screen.tsx
  packages/app/utils/userop.ts
Labels: bug, kwaii, feature, refactor

#1254 Lowercase token names on home page
  packages/app/data/coins.ts
  packages/app/features/home/TokenBalanceList.tsx
  packages/app/features/home/TokenDetails.tsx
  packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
Labels: kwaii, feature, refactor

#1187 Deposit redesign
  apps/next/pages/deposit/apple-pay.tsx
  apps/next/pages/deposit/crypto.tsx
  apps/next/pages/deposit/debit-card.tsx
  apps/next/pages/deposit/success.tsx
  apps/next/pages/deposit/success/index.tsx
  packages/app/components/icons/IconApple.tsx
  packages/app/components/icons/IconDebitCard.tsx
  packages/app/components/icons/IconWallet.tsx
  packages/app/components/icons/index.tsx
  packages/app/features/deposit/DepositCoinbase/DepositCoinbaseForm.tsx
  packages/app/features/deposit/DepositCoinbase/screen.test.tsx
  packages/app/features/deposit/DepositCoinbase/screen.tsx
  packages/app/features/deposit/__snapshots__/screen.test.tsx.snap
  packages/app/features/deposit/coinbase/screen.tsx
  packages/app/features/deposit/components/ApplePayIcon.tsx
  packages/app/features/deposit/components/CoinbaseOnrampVerifyScreen.tsx
  packages/app/features/deposit/components/CopyAddressDialog.tsx
  packages/app/features/deposit/components/DepositAddress.tsx
  packages/app/features/deposit/components/DepositAddressQR.tsx
  packages/app/features/deposit/components/DepositOptionButton.tsx
  packages/app/features/deposit/components/OnrampFlow.tsx
  packages/app/features/deposit/components/SuccessScreen.tsx
  packages/app/features/deposit/crypto/screen.tsx
  packages/app/features/deposit/screen.test.tsx
  packages/app/features/deposit/screen.tsx
  packages/app/features/deposit/success/screen.tsx
  packages/app/routers/params.tsx
Labels: kwaii, feature

#1255 Adjust to kyberswap API changes
  packages/api/src/routers/swap/types.ts
Labels: kwaii, refactor

#1259 Add quick actions on home screen on mobile
  packages/app/components/MobileButtonRowLayout.tsx
  packages/app/features/home/HomeQuickActions.tsx
  packages/app/features/home/TokenDetails.test.tsx
  packages/app/features/home/TokenDetails.tsx
  packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
  packages/app/features/home/screen.tsx
Labels: kwaii, feature, refactor

#1261 More unit tests for send screen
  packages/app/features/send/screen.test.tsx
Labels: kwaii, tests

#1262 Improved wallet address in crypto deposit on mobile
  packages/app/features/deposit/crypto/screen.tsx
Labels: kwaii, feature

#1265 Add hook to fetch multiple tokens market data
  packages/app/utils/coin-gecko/index.tsx
Labels: kwaii, feature

#1266 Add more data in token rows on home page
  packages/app/features/auth/components/VerifyCode.tsx
  packages/app/features/auth/onboarding/__snapshots__/screen.test.tsx.snap
  packages/app/features/auth/onboarding/onboarding-form.tsx
  packages/app/features/auth/sign-up/sign-up-form.tsx
  packages/app/features/home/HomeQuickActions.tsx
  packages/app/features/home/TokenBalanceCard.tsx
  packages/app/features/home/TokenBalanceList.tsx
  packages/app/features/home/__snapshots__/TokenDetails.test.tsx.snap
  packages/app/features/home/screen.tsx
  packages/ui/src/components/BigHeading.tsx
Labels: kwaii, feature, refactor

#1268 Use kyberswap prices in trade as fallback to coingecko and dexscreener
  packages/app/features/swap/form/screen.tsx
Labels: kwaii, feature, refactor

#1269 Add stub page for earn
  apps/next/pages/earn/index.tsx
  packages/app/components/ComingSoon.tsx
  packages/app/components/TopNav.tsx
Labels: kwaii, feature

#1270 Add coming soon page for sendpot
  apps/next/pages/sendpot/index.tsx
  packages/app/components/TopNav.tsx
Labels: kwaii, feature

#1271 Add coming soon page for feed
  apps/next/pages/feed/index.tsx
  packages/app/components/TopNav.tsx
Labels: kwaii, feature

#1273 Added invest page
  apps/next/pages/invest/index.tsx
  packages/app/components/TopNav.tsx
  packages/app/features/invest/screen.tsx
  packages/ui/src/components/LinkBanner.tsx
Labels: kwaii, feature

#1275 Added new pages to side bar
  packages/app/components/BottomTabBar/BottomNavBar.tsx
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: kwaii, feature

#1287 Megapot misc ux updates
  packages/app/features/sendpot/BuyTicketsScreen.tsx
  packages/app/features/sendpot/DrawingHistory.tsx
Labels: kwaii, feature

#1289 Total balance polishes
  packages/app/features/home/TokenBalanceCard.tsx
Labels: kwaii, refactor

#1290 Made invest and explore pages public
  apps/next/pages/explore/index.tsx
  apps/next/pages/invest/index.tsx
Labels: kwaii, feature

#1291 Fixed odd UI glitch on account page on desktop
  packages/app/features/account/__snapshots__/screen.test.tsx.snap
  packages/app/features/account/screen.tsx
Labels: bug, kwaii

#1292 Made top nav avatar click go to account page
  packages/app/components/TopNav.tsx
Labels: kwaii, feature, refactor

#1293 Removed word 'My' and search from activity page
  apps/next/pages/activity.tsx
  packages/app/features/activity/__snapshots__/screen.test.tsx.snap
  packages/app/features/activity/screen.test.tsx
  packages/app/features/activity/screen.tsx
Labels: kwaii, refactor

#1294 Increased notes font size to match iMessage
  packages/app/features/profile/__snapshots__/screen.test.tsx.snap
  packages/app/features/profile/screen.tsx
  packages/app/features/send/SendAmountForm.tsx
  packages/app/features/send/__snapshots__/screen.test.tsx.snap
  packages/app/features/send/confirm/screen.tsx
Labels: kwaii, feature

#1299 Aligned menu icons on desktop
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: kwaii, feature

#1300 Removed obsolete search on activity page test
  packages/playwright/tests/activity.onboarded.spec.ts
Labels: kwaii, refactor

#1311 Added bottom nav bar for tablets
  packages/app/components/BottomTabBar/BottomNavBar.tsx
  packages/app/features/account/screen.tsx
Labels: kwaii, feature, refactor

#1312 Fixed 'withdraw' word show for trades instead of trade in activity
  packages/app/features/activity/ActivityDetails.tsx
  packages/app/features/home/TokenActivityRow.tsx
  packages/app/utils/activity.ts
Labels: kwaii, feature, refactor

#1313 Aligned main pages headers to have larger text and no back button
  apps/next/pages/explore/index.tsx
  apps/next/pages/invest/index.tsx
  packages/app/components/TopNav.tsx
  packages/app/features/send/components/SendTopNav.tsx
Labels: kwaii, feature, refactor

#1315 Added back swap routers part of seeder
  packages/snaplet/bin/seed.ts
Labels: kwaii, feature

#1316 Put activity screen behind bottom nav bar
  packages/app/features/activity/RecentActivity.tsx
  packages/app/features/activity/__snapshots__/screen.test.tsx.snap
  packages/app/features/activity/screen.test.tsx
Labels: kwaii, feature, refactor, performance

#1317 Put account page behind bottom nav bar
  packages/app/features/account/__snapshots__/screen.test.tsx.snap
  packages/app/features/account/screen.tsx
Labels: kwaii, feature, refactor

#1319 Put settings pages behind bottom nav bar
  packages/app/features/account/settings/layout.web.tsx
Labels: kwaii, feature, refactor

#1327 Added account avatar on main send page on mobile
  packages/app/features/send/components/SendTopNav.tsx
Labels: kwaii, feature

#1329 Removed unnecessary spacing above bottom nav bar
  packages/app/features/account/sendtag/add/AddSendtagsScreen.tsx
  packages/app/features/account/sendtag/checkout/screen.tsx
  packages/app/features/account/sendtag/screen.tsx
  packages/app/features/deposit/__snapshots__/screen.test.tsx.snap
  packages/app/features/deposit/screen.tsx
  packages/app/features/earn/active/screen.tsx
  packages/app/features/earn/withdraw/screen.tsx
  packages/app/features/profile/__snapshots__/screen.test.tsx.snap
  packages/app/features/profile/screen.tsx
  packages/app/features/send/SendAmountForm.tsx
  packages/app/features/send/__snapshots__/screen.test.tsx.snap
  packages/app/features/send/confirm/screen.tsx
  packages/app/features/swap/form/__snapshots__/screen.test.tsx.snap
  packages/app/features/swap/form/screen.tsx
  packages/app/features/swap/summary/__snapshots__/screen.test.tsx.snap
  packages/app/features/swap/summary/screen.tsx
Labels: kwaii, refactor

#1330 Hid bottom nav bar when scrolling down
  packages/app/components/BottomTabBar/BottomNavBar.tsx
Labels: kwaii, feature

#1332 Fixed edit button not always working on trade page
  packages/app/features/swap/summary/__snapshots__/screen.test.tsx.snap
  packages/app/features/swap/summary/screen.tsx
Labels: bug, kwaii

#1333 Made edit button on trade page more accessible
  packages/app/features/swap/summary/__snapshots__/screen.test.tsx.snap
  packages/app/features/swap/summary/screen.tsx
Labels: kwaii, feature, refactor

#1334 Fixed settings edit pages width on desktop
  packages/app/features/account/components/editProfile/screen.tsx
  packages/app/features/account/settings/personal-info.tsx
Labels: bug, kwaii, refactor

#1335 Changed default send token to send if user has balance
  packages/app/routers/params.tsx
Labels: kwaii, feature, refactor

#1336 Cleaned up side menu on desktop
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: kwaii, feature, refactor

#1337 Better UX in account menu entry on desktop
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: kwaii, feature, refactor

#1338 Fixed account menu entry background issue on desktop
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: bug, kwaii

#1339 Aligned desktop home page with mobile
  packages/app/features/home/HomeQuickActions.tsx
  packages/app/features/home/TokenDetails.test.tsx
  packages/app/features/home/TokenDetails.tsx
  packages/app/features/home/screen.tsx
Labels: kwaii, feature, refactor

#1376 Fixed hover styles type issue
  packages/app/components/FormFields/CoinField.tsx
  packages/app/components/SearchBar.tsx
  packages/app/components/sidebar/HomeSideBar.tsx
  packages/app/features/account/screen.tsx
  packages/app/features/account/settings/SettingsNavLink.tsx
  packages/app/features/deposit/components/DepositOptionButton.tsx
  packages/app/features/home/HomeQuickActions.tsx
  packages/app/features/home/TokenActivityRow.tsx
  packages/app/features/home/TokenBalanceList.tsx
  packages/app/features/swap/form/screen.tsx
  packages/app/utils/useHoverStyles.ts
Labels: bug, kwaii, refactor

#1377 Show notes in activity page
  packages/app/features/home/TokenActivityRow.tsx
  packages/app/features/profile/screen.tsx
  packages/app/utils/activity.ts
Labels: kwaii, feature, refactor

#1389 UI changes in menu on desktop
  packages/app/components/BottomTabBar/BottomNavBar.tsx
  packages/app/components/FormFields/CoinField.tsx
  packages/app/components/sidebar/HomeSideBar.tsx
  packages/app/components/sidebar/SideBarNavLink.tsx
  packages/app/features/swap/form/screen.tsx
  packages/app/utils/useHoverStyles.ts
Labels: kwaii, feature, refactor

#1393 Fixed history avatar position
  packages/app/features/profile/screen.tsx
Labels: bug, kwaii, refactor

#1396 Redesigned account page
  apps/expo/app/settings/index.tsx
  apps/next/pages/account/backup/confirm/[cred_id].tsx
  apps/next/pages/account/backup/create.tsx
  apps/next/pages/account/backup/index.tsx
  apps/next/pages/account/edit-profile.tsx
  apps/next/pages/account/personal-info.tsx
  apps/next/pages/account/settings/backup/confirm/[cred_id].tsx
  apps/next/pages/account/settings/index.tsx
  packages/app/components/ReferralLink.tsx
  packages/app/features/account/AccountScreenLayout.tsx
  packages/app/features/account/backup/confirm.tsx
  packages/app/features/account/backup/create.tsx
  packages/app/features/account/backup/index.tsx
  packages/app/features/account/components/AccountHeader.tsx
  packages/app/features/account/components/AccountLinks.tsx
  packages/app/features/account/components/AccountNavLink.tsx
  packages/app/features/account/components/FieldWithLabel.tsx
  packages/app/features/account/components/ReadOnlyFieldWithLabel.tsx
  packages/app/features/account/components/SettingsHeader.tsx
  packages/app/features/account/components/editProfile/screen.tsx
  packages/app/features/account/components/personalInfo/screen.tsx
  packages/app/features/account/general-screen.tsx
  packages/app/features/account/screen.skiptest.tsx
  packages/app/features/account/screen.tsx
  packages/app/features/account/settings/edit-profile.tsx
  packages/app/features/account/settings/index.tsx
  packages/app/features/account/settings/layout.web.tsx
  packages/playwright/tests/account-settings-backup.onboarded.spec.ts
  packages/playwright/tests/account.logged-in.spec.ts
Labels: kwaii, feature, refactor

#1397 Changed explore icon
  packages/app/components/icons/IconWorldSearch.tsx
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: kwaii, feature

#1399 Added slashes on all assets
  packages/app/features/home/TokenBalanceCard.tsx
  packages/app/features/home/TokenBalanceList.tsx
  packages/app/features/home/screen.tsx
  packages/app/features/home/utils/useIsPriceHidden.tsx
Labels: kwaii, feature

#1403 Changed referral texts
  apps/next/pages/account/affiliate.tsx
  packages/app/features/account/components/AccountHeader.tsx
  packages/app/features/account/components/AccountLinks.tsx
  packages/app/features/affiliate/screen.tsx
Labels: kwaii, feature, refactor

#1405 Allowed users send to themselves from transactions history
  packages/app/features/profile/screen.tsx
Labels: kwaii, feature

#1406 Added spinners when temporal transfer is pending
  packages/app/features/activity/ActivityDetails.tsx
  packages/app/features/home/TokenActivityRow.tsx
  packages/app/features/profile/screen.tsx
  packages/app/utils/activity.tsx
Labels: kwaii, feature, refactor

#1407 Fix activity spinner position
  packages/app/features/profile/screen.tsx
Labels: bug, kwaii, refactor

#1408 Added send id to account page when no send tags
  packages/app/components/ReferralLink.tsx
  packages/app/features/account/components/AccountHeader.tsx
Labels: kwaii, feature, refactor

#1409 Added transfer direction indicator
  packages/app/components/ReferralLink.tsx
  packages/app/features/activity/ActivityAvatar.tsx
  packages/app/features/activity/utils/__mocks__/mock-activity-feed.ts
  packages/app/utils/activity.test.ts
  packages/app/utils/activity.tsx
  packages/app/utils/zod/activity/__snapshots__/index.test.ts.snap
Labels: kwaii, feature, refactor

#1410 Reorder menu items on desktop
  packages/app/components/sidebar/HomeSideBar.tsx
Labels: kwaii, feature

#1411 Removed rewards header
  packages/app/features/explore/rewards/activity/screen.tsx
Labels: kwaii, refactor

#1412 Hide account and activity buttons in nav on activity page
  apps/next/pages/account/index.tsx
  packages/app/components/TopNav.tsx
Labels: kwaii, feature

#1415 Removed transfer direction indicator
  packages/app/features/activity/ActivityAvatar.tsx
  packages/app/utils/activity.tsx
Labels: kwaii, refactor
